# Dropboxからのダウンロードは行なわない。（面倒なのと誰のアカウントを使うかという問題がある）

bin = "./target/test-with-generated-opts/bin/{}"
testcases = "./target/test-with-generated-opts/testcases/{}"

[examples.abc054-c]
name = "ABC054: C - One-stroke Path"
url = "https://atcoder.jp/contests/abc054/tasks/abc054_c"
matching = "Words"

[examples.abc057-b]
name = "ABC057: B - Checkpoints"
url = "https://atcoder.jp/contests/abc057/tasks/abc057_b"
matching = "Words"

[examples.abc084-d]
name = "ABC084: D - 2017-like Number"
url = "https://atcoder.jp/contests/abc084/tasks/abc084_d"
matching = "Words"

[examples.abc118-b]
name = "ABC118: B - Foods Loved by Everyone"
url = "https://atcoder.jp/contests/abc118/tasks/abc118_b"
matching = "Words"

[examples.abc120-d]
name = "ABC120: D - Decayed Bridges"
url = "https://atcoder.jp/contests/abc120/tasks/abc120_d"
matching = "Words"

[examples.abc121-b]
name = "ABC121: B - Can you solve this?"
url = "https://atcoder.jp/contests/abc121/tasks/abc121_b"
matching = "Words"

[examples.abc129-f]
name = "ABC129: F - Takahashi's Basics in Education and Learning"
url = "https://atcoder.jp/contests/abc129/tasks/abc129_f"
matching = "Words"

[examples.abc142-d]
name = "ABC142: D - Disjoint Set of Common Divisors"
url = "https://atcoder.jp/contests/abc142/tasks/abc142_d"
matching = "Words"

[examples.abc144-d]
name = "ABC144: D - Water Bottle"
url = "https://atcoder.jp/contests/abc144/tasks/abc144_d"
matching = { FloatOr = { abs = 1e-6, rel = 1e-6 } }

[examples.apg4b-a]
name = "APG4b: A - 1.00.はじめに"
url = "https://atcoder.jp/contests/APG4b/tasks/APG4b_a"
matching = "Exact"
alt_testcases = [{ in = "", out = "Hello, world!\n" }]

[examples.apg4b-ex25]
name = "APG4b: EX25 - 集合の操作 / 3.05"
url = "https://atcoder.jp/contests/APG4b/tasks/APG4b_bx"
matching = "Words"

[examples.apg4b-ex26]
name = "APG4b: EX26 - 電卓を作ろう3 / 3.06"
url = "https://atcoder.jp/contests/APG4b/tasks/APG4b_bw"
matching = "Exact"

[examples.arc065-c]
name = "ABC049 / ARC065: C - 白昼夢 / Daydream"
url = "https://atcoder.jp/contests/arc065/tasks/arc065_a"
matching = "Words"

[examples.arc084-c]
name = "ABC077 / ARC084: C - Snuke Festival"
url = "https://atcoder.jp/contests/arc084/tasks/arc084_a"
matching = "Words"

[examples.atc001-b]
name = "ATC001: B - Union Find"
url = "https://atcoder.jp/contests/atc001/tasks/unionfind_a"
matching = "Words"

[examples.atc002-b]
name = "ATC002: B - n^p mod m"
url = "https://atcoder.jp/contests/atc002/tasks/atc002_b"
matching = "Words"

[examples.sumitrust2019-c]
name = "Sumitomo Mitsui Trust Bank Programming Contest 2019: C - 100 to 105"
url = "https://atcoder.jp/contests/sumitrust2019/tasks/sumitb2019_c"
matching = "Words"
