name: CI

on:
  schedule:
    - cron: '0 0 1 * *'
  push:
  pull_request:

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup 1.42.0-x86_64-unknown-linux-gnu
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.42.0-x86_64-unknown-linux-gnu
          override: true
          profile: minimal
          components: rustfmt

      - name: '`cargo fmt -- --check`'
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

      - name: '`cargo fmt --manifest-path ./xtask/Cargo.toml -- --check`'
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path ./xtask/Cargo.toml -- --check

  build:
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - 1.42.0-x86_64-pc-windows-msvc
          - 1.42.0-x86_64-apple-darwin
          - 1.42.0-x86_64-unknown-linux-gnu
        include:
          - toolchain: 1.42.0-x86_64-pc-windows-msvc
            os: windows-latest
          - toolchain: 1.42.0-x86_64-apple-darwin
            os: macOS-latest
          - toolchain: 1.42.0-x86_64-unknown-linux-gnu
            os: ubuntu-18.04

    name: ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: '`git config --global core.autocrlf false`'
        run: git config --global core.autocrlf false
        if: matrix.os == 'windows-latest'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup ${{ matrix.toolchain }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          profile: minimal
          components: clippy

      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: '`cargo clippy --all-targets --profile test -- -D warnings`'
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --profile test -- -D warnings

      - name: '`cargo clippy --manifest-path ./xtask/Cargo.toml -- -D warnings`'
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path ./xtask/Cargo.toml -- -D warnings

      - name: '`cargo test --all-targets --no-fail-fast`'
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-targets --no-fail-fast

      - name: '`cargo run --release`'
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --release

      - name: '`cargo xtask test-examples`'
        uses: actions-rs/cargo@v1
        with:
          command: xtask
          args: test-examples
